/*
# Create private documents storage bucket

1. New Storage
- Creates a private bucket `documents` for psychologist verification files (diplomas, certificates).
- Public read is OFF; access is via signed URLs generated by the frontend with the anon key.
2. Notes
- The bucket is inserted into `storage.buckets`. RLS on storage.objects defaults to restricting access; the anon-key client can still upload and create signed URLs because the prototype uses open policies below.
*/

INSERT INTO storage.buckets (id, name, public)
VALUES ('documents', 'documents', false)
ON CONFLICT (id) DO NOTHING;

-- Allow anon/authenticated to CRUD objects in the documents bucket (prototype, shared data)
DROP POLICY IF EXISTS "anon_read_documents_bucket" ON storage.objects;
CREATE POLICY "anon_read_documents_bucket" ON storage.objects
  FOR SELECT TO anon, authenticated USING (bucket_id = 'documents');

DROP POLICY IF EXISTS "anon_insert_documents_bucket" ON storage.objects;
CREATE POLICY "anon_insert_documents_bucket" ON storage.objects
  FOR INSERT TO anon, authenticated WITH CHECK (bucket_id = 'documents');

DROP POLICY IF EXISTS "anon_update_documents_bucket" ON storage.objects;
CREATE POLICY "anon_update_documents_bucket" ON storage.objects
  FOR UPDATE TO anon, authenticated USING (bucket_id = 'documents') WITH CHECK (bucket_id = 'documents');

DROP POLICY IF EXISTS "anon_delete_documents_bucket" ON storage.objects;
CREATE POLICY "anon_delete_documents_bucket" ON storage.objects
  FOR DELETE TO anon, authenticated USING (bucket_id = 'documents');
